# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, confloat


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: Optional[str] = Field("", title="Workflow Description")


class PatrolObs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    file_path: str = Field(
        ...,
        description="Path to the file to load. Supported formats: .parquet, .geoparquet, .geojson, .json, .gpkg, .csv, .shp",
        title="File Path",
    )
    layer: Optional[str] = Field(
        None,
        description="Layer name for GeoPackage files (optional, only used for .gpkg files)",
        title="Layer",
    )
    deserialize_json: Optional[bool] = Field(
        False,
        description="Whether to deserialize JSON strings back to Python objects (lists, dicts). Set to True when loading files saved by persist_df_wrapper, which serializes complex objects to JSON.",
        title="Deserialize Json",
    )


class CustomizeColumnsTraj(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    drop_columns: Optional[List[str]] = Field(
        [], description="List of columns to drop.", title="Drop Columns"
    )


class SqlQueryTraj(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    query: Optional[str] = Field(
        "",
        description="SQL query string to apply to the DataFrame. Leaves it unchanged when the field is emptyUse 'df' as the table name in the query.",
        title="SQL Query",
    )
    columns: Optional[List[str]] = Field(
        None,
        description="Optional list of column names to include in the SQL query context. If specified, only these columns will be available in the 'df' table for querying. Use this to exclude columns with unsupported data types (list, dict) that cannot be stored in SQLite. If not specified, all columns are included.",
        title="Columns",
    )


class SetPatrolTrajColorColumn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    var: str = Field(
        ...,
        description="Select the patrol observation attribute to use for categorizing and coloring patrol trajectories on the generated maps.",
        title="Category",
    )


class Filetype(str, Enum):
    csv = "csv"
    gpkg = "gpkg"
    geoparquet = "geoparquet"
    parquet = "parquet"


class PersistPatrolTraj(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    filetypes: Optional[List[Filetype]] = Field(
        ["parquet"], description="The output format", title="Filetypes"
    )


class SetSkipMap(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    var: bool = Field(
        ...,
        description="Skip generating maps for patrol trajectories. Recommended for large datasets to improve performance.",
        title="",
    )


class GenerateMaps(BaseModel):
    set_skip_map: Optional[SetSkipMap] = Field(None, title="Skip Map Generation")


class CreatePatrolReport(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    template_path: str = Field(
        ...,
        description="Path or URL to the Word template (.docx) file with Jinja2 placeholders. Supports local paths and remote URLs (http://, https://).",
        title="Template Path",
    )


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class TrajectorySegmentFilter(BaseModel):
    min_length_meters: Optional[confloat(ge=0.001)] = Field(
        0.001, title="Minimum Segment Length (Meters)"
    )
    max_length_meters: Optional[confloat(gt=0.001)] = Field(
        100000, title="Maximum Segment Length (Meters)"
    )
    min_time_secs: Optional[confloat(ge=1.0)] = Field(
        1, title="Minimum Segment Duration (Seconds)"
    )
    max_time_secs: Optional[confloat(gt=1.0)] = Field(
        172800, title="Maximum Segment Duration (Seconds)"
    )
    min_speed_kmhr: Optional[confloat(gt=0.001)] = Field(
        0.01, title="Minimum Segment Speed (Kilometers per Hour)"
    )
    max_speed_kmhr: Optional[confloat(gt=0.001)] = Field(
        500, title="Maximum Segment Speed (Kilometers per Hour)"
    )


class SpatialGrouper(BaseModel):
    spatial_index_name: str = Field(..., title="Spatial Regions")


class TemporalGrouper(BaseModel):
    temporal_index: str = Field(..., title="Time")


class ValueGrouper(BaseModel):
    index_name: str = Field(..., title="Category")


class AxisStyle(BaseModel):
    title: Optional[str] = Field(None, title="Title")
    range: Optional[List[float]] = Field(None, title="Range")


class LayoutStyle(BaseModel):
    font_size: Optional[float] = Field(None, title="Font Size")
    font_color: Optional[str] = Field(None, title="Font Color")
    font_style: Optional[str] = Field(None, title="Font Style")
    plot_bgcolor: Optional[str] = Field(None, title="Plot Bgcolor")
    showlegend: Optional[bool] = Field(None, title="Showlegend")
    hovermode: Optional[str] = Field(None, title="Hovermode")
    legend_title: Optional[str] = Field(None, title="Legend Title")
    title: Optional[str] = Field(None, title="Title")
    title_x: Optional[float] = Field(None, title="Title X")
    title_y: Optional[float] = Field(None, title="Title Y")
    xaxis: Optional[AxisStyle] = Field(None, title="Xaxis")
    yaxis: Optional[AxisStyle] = Field(None, title="Yaxis")


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: Optional[TimezoneInfo] = Field(None, title="Timezone")


class PatrolTraj(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    trajectory_segment_filter: Optional[TrajectorySegmentFilter] = Field(
        default_factory=lambda: TrajectorySegmentFilter.model_validate(
            {
                "min_length_meters": 0.001,
                "max_length_meters": 100000,
                "min_time_secs": 1,
                "max_time_secs": 172800,
                "min_speed_kmhr": 0.01,
                "max_speed_kmhr": 500,
            }
        ),
        description="Filter track data by setting limits on track segment length, duration, and speed. Segments outside these bounds are removed, reducing noise and to focus on meaningful movement patterns.",
        title=" ",
    )


class Groupers(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    groupers: Optional[List[Union[ValueGrouper, TemporalGrouper]]] = Field(
        None,
        description="            Specify how the data should be grouped to create the views for your dashboard.\n            This field is optional; if left blank, all the data will appear in a single view.\n            ",
        title=" ",
    )


class ProcessPatrolObservations(BaseModel):
    patrol_traj: Optional[PatrolTraj] = Field(None, title="Trajectory Segment Filter")
    customize_columns_traj: Optional[CustomizeColumnsTraj] = Field(
        None, title="Process Columns"
    )
    sql_query_traj: Optional[SqlQueryTraj] = Field(None, title="Apply SQL Query")
    groupers: Optional[Groupers] = Field(None, title="Group Data")
    set_patrol_traj_color_column: Optional[SetPatrolTrajColorColumn] = Field(
        None, title="Style Trajectory By Category"
    )


class PatrolBarChart(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    layout_kwargs: Optional[LayoutStyle] = Field(
        None,
        description="Additional kwargs passed to plotly.go.Figure(layout).",
        title="Layout Kwargs",
    )


class TransportSummary(BaseModel):
    patrol_bar_chart: Optional[PatrolBarChart] = Field(
        None, title="Draw Station Bar Chart"
    )


class FormData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: Optional[WorkflowDetails] = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Workflow Details",
    )
    time_range: Optional[TimeRange] = Field(
        None, description="Choose the period of time to analyze.", title="Time Range"
    )
    patrol_obs: Optional[PatrolObs] = Field(None, title="Load Patrol Observations")
    Process_Patrol_Observations: Optional[ProcessPatrolObservations] = Field(
        None,
        alias="Process Patrol Observations",
        description="Process patrol observations by applying filters, column transformations, and SQL queries.",
    )
    persist_patrol_traj: Optional[PersistPatrolTraj] = Field(
        None, title="Persist Patrol Trajectories"
    )
    Generate_Maps: Optional[GenerateMaps] = Field(
        None,
        alias="Generate Maps",
        description="Generate maps to visualize patrol trajectories.",
    )
    Transport_Summary: Optional[TransportSummary] = Field(
        None,
        alias="Transport Summary",
        description="Summarize patrol data by transport type and generate a bar chart.",
    )
    create_patrol_report: Optional[CreatePatrolReport] = Field(
        None, title="Create Patrol Report"
    )
