# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, confloat


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: str | None = Field("", title="Workflow Description")


class WriteFiletype(str, Enum):
    csv = "csv"
    gpkg = "gpkg"
    geoparquet = "geoparquet"


class PatrolObs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ca_uuid: str = Field(
        ..., description="Conservation Area UUID", title="Conservation Area UUID"
    )
    language_uuid: str = Field(..., description="Language UUID", title="Language UUID")
    patrol_mandate: str | None = Field(
        None, description="Patrol Mandate", title="Patrol Mandate"
    )
    patrol_transport: str | None = Field(
        None, description="Patrol Transport", title="Patrol Transport"
    )
    read_path: str | None = Field(
        None,
        description="Optional file path to read data from instead of fetching from SMART API. Supported formats: .parquet, .geoparquet, .geojson, .json, .gpkg, .csv",
        title="Read Path",
    )
    persist: bool | None = Field(
        False,
        description="Whether to persist the data to disk. Requires write_path to be set.",
        title="Persist",
    )
    write_path: str | None = Field(
        None,
        description="Optional root path to persist the data to.",
        title="Write Path",
    )
    write_filetypes: list[WriteFiletype] | None = Field(
        ["csv"],
        description="Output file formats when writing. Only used if write_path is provided.",
        title="Write Filetypes",
    )
    write_filename_prefix: str | None = Field(
        None,
        description="Optional filename prefix when writing. A hash suffix will be added automatically.",
        title="Write Filename Prefix",
    )
    write_sanitize: bool | None = Field(
        False,
        description="Whether to sanitize the dataframe for Arrow compatibility before persisting. Recommended when including observation details.",
        title="Write Sanitize",
    )


class CustomizeColumnsTraj(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    drop_columns: list[str] | None = Field(
        [], description="List of columns to drop.", title="Drop Columns"
    )


class SqlQueryTraj(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    query: str | None = Field(
        "",
        description="SQL query string to apply to the DataFrame. Leaves it unchanged when the field is emptyUse 'df' as the table name in the query.",
        title="SQL Query",
    )
    columns: list[str] | None = Field(
        None,
        description="Optional list of column names to include in the SQL query context. If specified, only these columns will be available in the 'df' table for querying. Use this to exclude columns with unsupported data types (list, dict) that cannot be stored in SQLite. If not specified, all columns are included.",
        title="Columns",
    )


class SetPatrolTrajColorColumn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    var: str = Field(
        ...,
        description="Select the patrol observation attribute to use for categorizing and coloring patrol trajectories on the generated maps.",
        title="Category",
    )


class Filetype(str, Enum):
    csv = "csv"
    gpkg = "gpkg"
    geoparquet = "geoparquet"
    parquet = "parquet"


class PersistPatrolTraj(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    filetypes: list[Filetype] | None = Field(
        ["parquet"], description="The output format", title="Filetypes"
    )


class SetSkipMap(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    var: bool = Field(
        ...,
        description="Skip generating maps for patrol trajectories. Recommended for large datasets to improve performance.",
        title="",
    )


class GenerateMaps(BaseModel):
    set_skip_map: SetSkipMap | None = Field(None, title="Skip Map Generation")


class CreatePatrolReport(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    template_path: str = Field(
        ...,
        description="Path or URL to the Word template (.docx) file with Jinja2 placeholders. Supports local paths and remote URLs (http://, https://).",
        title="Template Path",
    )


class SMARTConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class TrajectorySegmentFilter(BaseModel):
    min_length_meters: confloat(ge=0.001) | None = Field(
        0.001, title="Minimum Segment Length (Meters)"
    )
    max_length_meters: confloat(gt=0.001) | None = Field(
        100000, title="Maximum Segment Length (Meters)"
    )
    min_time_secs: confloat(ge=1.0) | None = Field(
        1, title="Minimum Segment Duration (Seconds)"
    )
    max_time_secs: confloat(gt=1.0) | None = Field(
        172800, title="Maximum Segment Duration (Seconds)"
    )
    min_speed_kmhr: confloat(gt=0.001) | None = Field(
        0.01, title="Minimum Segment Speed (Kilometers per Hour)"
    )
    max_speed_kmhr: confloat(gt=0.001) | None = Field(
        500, title="Maximum Segment Speed (Kilometers per Hour)"
    )


class SpatialGrouper(BaseModel):
    spatial_index_name: str = Field(..., title="Spatial Regions")


class TemporalIndex(str, Enum):
    Year__example__2024_ = "%Y"
    Month__example__September_ = "%B"
    Year_and_Month__example__2023_01_ = "%Y-%m"
    Day_of_the_year_as_a_number__example__365_ = "%j"
    Day_of_the_month_as_a_number__example__31_ = "%d"
    Day_of_the_week__example__Sunday_ = "%A"
    Hour__24_hour_clock__as_number__example__22_ = "%H"
    Date__example__2025_01_31_ = "%Y-%m-%d"


class TemporalGrouper(BaseModel):
    temporal_index: TemporalIndex = Field(..., title="Time")


class ValueGrouper(BaseModel):
    index_name: str = Field(..., title="Category")


class AxisStyle(BaseModel):
    title: str | None = Field(None, title="Title")
    range: list[float] | None = Field(None, title="Range")


class LayoutStyle(BaseModel):
    font_size: float | None = Field(None, title="Font Size")
    font_color: str | None = Field(None, title="Font Color")
    font_style: str | None = Field(None, title="Font Style")
    plot_bgcolor: str | None = Field(None, title="Plot Bgcolor")
    showlegend: bool | None = Field(None, title="Showlegend")
    hovermode: str | None = Field(None, title="Hovermode")
    legend_title: str | None = Field(None, title="Legend Title")
    title: str | None = Field(None, title="Title")
    title_x: float | None = Field(None, title="Title X")
    title_y: float | None = Field(None, title="Title Y")
    xaxis: AxisStyle | None = Field(None, title="Xaxis")
    yaxis: AxisStyle | None = Field(None, title="Yaxis")


class SmartClientName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: SMARTConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: TimezoneInfo | None = Field(None, title="Timezone")


class PatrolTraj(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    trajectory_segment_filter: TrajectorySegmentFilter | None = Field(
        default_factory=lambda: TrajectorySegmentFilter.model_validate(
            {
                "min_length_meters": 0.001,
                "max_length_meters": 100000,
                "min_time_secs": 1,
                "max_time_secs": 172800,
                "min_speed_kmhr": 0.01,
                "max_speed_kmhr": 500,
            }
        ),
        description="Filter track data by setting limits on track segment length, duration, and speed. Segments outside these bounds are removed, reducing noise and to focus on meaningful movement patterns.",
        title=" ",
    )


class Groupers(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    groupers: list[ValueGrouper | TemporalGrouper] | None = Field(
        None,
        description="            Specify how the data should be grouped to create the views for your dashboard.\n            This field is optional; if left blank, all the data will appear in a single view.\n            ",
        title=" ",
    )


class ProcessPatrolObservations(BaseModel):
    patrol_traj: PatrolTraj | None = Field(None, title="Trajectory Segment Filter")
    customize_columns_traj: CustomizeColumnsTraj | None = Field(
        None, title="Process Columns"
    )
    sql_query_traj: SqlQueryTraj | None = Field(None, title="Apply SQL Query")
    groupers: Groupers | None = Field(None, title="Group Data")
    set_patrol_traj_color_column: SetPatrolTrajColorColumn | None = Field(
        None, title="Style Trajectory By Category"
    )


class PatrolBarChart(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    layout_kwargs: LayoutStyle | None = Field(
        None,
        description="Additional kwargs passed to plotly.go.Figure(layout).",
        title="Layout Kwargs",
    )


class TransportSummary(BaseModel):
    patrol_bar_chart: PatrolBarChart | None = Field(
        None, title="Draw Transport Bar Chart"
    )


class FormData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: WorkflowDetails | None = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Workflow Details",
    )
    smart_client_name: SmartClientName | None = Field(None, title="Data Source")
    time_range: TimeRange | None = Field(
        None, description="Choose the period of time to analyze.", title="Time Range"
    )
    patrol_obs: PatrolObs | None = Field(None, title="Get Patrol Observations")
    Process_Patrol_Observations: ProcessPatrolObservations | None = Field(
        None,
        alias="Process Patrol Observations",
        description="Process patrol observations by applying filters, column transformations, and SQL queries.",
    )
    persist_patrol_traj: PersistPatrolTraj | None = Field(
        None, title="Persist Patrol Trajectories"
    )
    Generate_Maps: GenerateMaps | None = Field(
        None,
        alias="Generate Maps",
        description="Generate maps to visualize patrol trajectories.",
    )
    Transport_Summary: TransportSummary | None = Field(
        None,
        alias="Transport Summary",
        description="Summarize patrol data by transport type and generate a bar chart.",
    )
    create_patrol_report: CreatePatrolReport | None = Field(
        None, title="Create Patrol Report"
    )
