# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Mt Patrols
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.config import set_string_var as set_string_var
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import (
    set_smart_connection as set_smart_connection,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope_workflows_core.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_custom.tasks.results import create_docx as create_docx
from ecoscope_workflows_ext_custom.tasks.transformation import (
    drop_column_prefix as drop_column_prefix,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_patrol_observations_from_smart as get_patrol_observations_from_smart,
)
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    create_polyline_layer as create_polyline_layer,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_bar_chart as draw_bar_chart,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_ecomap as draw_ecomap
from ecoscope_workflows_ext_ecoscope.tasks.results import set_base_maps as set_base_maps
from ecoscope_workflows_ext_ecoscope.tasks.skip import (
    all_geometry_are_none as all_geometry_are_none,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)

# %% [markdown]
# ## Workflow Details

# %%
# parameters

workflow_details_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


workflow_details = (
    set_workflow_details.set_task_instance_id("workflow_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**workflow_details_params)
    .call()
)


# %% [markdown]
# ## Data Source

# %%
# parameters

smart_client_name_params = dict(
    data_source=...,
)

# %%
# call the task


smart_client_name = (
    set_smart_connection.set_task_instance_id("smart_client_name")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**smart_client_name_params)
    .call()
)


# %% [markdown]
# ## Time Range

# %%
# parameters

time_range_params = dict(
    since=...,
    until=...,
    timezone=...,
)

# %%
# call the task


time_range = (
    set_time_range.set_task_instance_id("time_range")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(time_format="%d %b %Y %H:%M:%S %Z", **time_range_params)
    .call()
)


# %% [markdown]
# ## Get Patrol Observations

# %%
# parameters

patrol_obs_params = dict(
    patrol_mandate=...,
    patrol_transport=...,
)

# %%
# call the task


patrol_obs = (
    get_patrol_observations_from_smart.set_task_instance_id("patrol_obs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        client=smart_client_name,
        time_range=time_range,
        ca_uuid="",
        language_uuid="",
        **patrol_obs_params,
    )
    .call()
)


# %% [markdown]
# ## Extract Timezone Selection

# %%
# parameters

get_timezone_params = dict()

# %%
# call the task


get_timezone = (
    get_timezone_from_time_range.set_task_instance_id("get_timezone")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(time_range=time_range, **get_timezone_params)
    .call()
)


# %% [markdown]
# ## Convert Patrol Observations to Timezone

# %%
# parameters

convert_patrols_to_user_timezone_params = dict()

# %%
# call the task


convert_patrols_to_user_timezone = (
    convert_values_to_timezone.set_task_instance_id("convert_patrols_to_user_timezone")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=patrol_obs,
        timezone=get_timezone,
        columns=["fixtime"],
        **convert_patrols_to_user_timezone_params,
    )
    .call()
)


# %% [markdown]
# ## Remove Column Prefix Extra

# %%
# parameters

drop_extra_prefix_obs_params = dict()

# %%
# call the task


drop_extra_prefix_obs = (
    drop_column_prefix.set_task_instance_id("drop_extra_prefix_obs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=convert_patrols_to_user_timezone,
        prefix="extra__",
        duplicate_strategy="suffix",
        **drop_extra_prefix_obs_params,
    )
    .call()
)


# %% [markdown]
# ## Filter Observation Relocations

# %%
# parameters

filter_patrol_obs_params = dict()

# %%
# call the task


filter_patrol_obs = (
    apply_reloc_coord_filter.set_task_instance_id("filter_patrol_obs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=drop_extra_prefix_obs,
        roi_gdf=None,
        roi_name=None,
        reset_index=False,
        bounding_box={"min_x": -180.0, "max_x": 180.0, "min_y": -90.0, "max_y": 90.0},
        filter_point_coords=[
            {"x": 180.0, "y": 90.0},
            {"x": 0.0, "y": 0.0},
            {"x": 1.0, "y": 1.0},
        ],
        **filter_patrol_obs_params,
    )
    .call()
)


# %% [markdown]
# ## Trajectory Segment Filter

# %%
# parameters

patrol_traj_params = dict(
    trajectory_segment_filter=...,
)

# %%
# call the task


patrol_traj = (
    relocations_to_trajectory.set_task_instance_id("patrol_traj")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(relocations=filter_patrol_obs, **patrol_traj_params)
    .call()
)


# %% [markdown]
# ## Remove Column Prefix Extra

# %%
# parameters

drop_extra_prefix_traj_params = dict()

# %%
# call the task


drop_extra_prefix_traj = (
    drop_column_prefix.set_task_instance_id("drop_extra_prefix_traj")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=patrol_traj,
        prefix="extra__",
        duplicate_strategy="suffix",
        **drop_extra_prefix_traj_params,
    )
    .call()
)


# %% [markdown]
# ## Internally Process Columns

# %%
# parameters

customize_columns_internally_params = dict()

# %%
# call the task


customize_columns_internally = (
    map_columns.set_task_instance_id("customize_columns_internally")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=drop_extra_prefix_traj,
        rename_columns={},
        drop_columns=["id"],
        retain_columns=[],
        raise_if_not_found=False,
        **customize_columns_internally_params,
    )
    .call()
)


# %% [markdown]
# ## Add temporal index to Patrol Trajectories

# %%
# parameters

traj_add_temporal_index_params = dict()

# %%
# call the task


traj_add_temporal_index = (
    add_temporal_index.set_task_instance_id("traj_add_temporal_index")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=customize_columns_internally,
        time_col="segment_start",
        groupers=[{"index_name": "patrol_mandate"}],
        cast_to_datetime=True,
        format="mixed",
        **traj_add_temporal_index_params,
    )
    .call()
)


# %% [markdown]
# ## Patrol Traj Colormap

# %%
# parameters

traj_colormap_params = dict()

# %%
# call the task


traj_colormap = (
    apply_color_map.set_task_instance_id("traj_colormap")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=traj_add_temporal_index,
        colormap=[
            "#FF9600",
            "#F23B0E",
            "#A100CB",
            "#F04564",
            "#03421A",
            "#3089FF",
            "#E26FFF",
            "#8C1700",
            "#002960",
            "#FFD000",
            "#B62879",
            "#680078",
            "#005A56",
            "#0056C7",
            "#331878",
            "#E76826",
        ],
        input_column_name="station",
        output_column_name="patrol_traj_colormap",
        **traj_colormap_params,
    )
    .call()
)


# %% [markdown]
# ## Split Patrol Trajectories by Group

# %%
# parameters

split_patrol_traj_groups_params = dict()

# %%
# call the task


split_patrol_traj_groups = (
    split_groups.set_task_instance_id("split_patrol_traj_groups")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=traj_colormap,
        groupers=[{"index_name": "patrol_mandate"}],
        **split_patrol_traj_groups_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Patrol Trajectories

# %%
# parameters

persist_patrol_traj_params = dict(
    filename=...,
    filetypes=...,
)

# %%
# call the task


persist_patrol_traj = (
    persist_df_wrapper.set_task_instance_id("persist_patrol_traj")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_prefix="patrol_trajectories",
        sanitize=True,
        **persist_patrol_traj_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_patrol_traj_groups)
)


# %% [markdown]
# ## Set Patrol Map Title

# %%
# parameters

set_patrol_map_title_params = dict()

# %%
# call the task


set_patrol_map_title = (
    set_string_var.set_task_instance_id("set_patrol_map_title")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(var="Patrol Trajectories Map", **set_patrol_map_title_params)
    .call()
)


# %% [markdown]
# ## Base Maps

# %%
# parameters

base_map_defs_params = dict(
    base_maps=...,
)

# %%
# call the task


base_map_defs = (
    set_base_maps.set_task_instance_id("base_map_defs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**base_map_defs_params)
    .call()
)


# %% [markdown]
# ## Rename Trajectory Columns for Display

# %%
# parameters

rename_traj_display_columns_params = dict()

# %%
# call the task


rename_traj_display_columns = (
    map_columns.set_task_instance_id("rename_traj_display_columns")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        drop_columns=[],
        retain_columns=[],
        raise_if_not_found=False,
        rename_columns={
            "segment_start": "Start Time",
            "timespan_seconds": "Duration (s)",
            "speed_kmhr": "Speed (kph)",
        },
        **rename_traj_display_columns_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_patrol_traj_groups)
)


# %% [markdown]
# ## Create Trajectory Map Layers

# %%
# parameters

patrol_traj_map_layers_params = dict(
    zoom=...,
)

# %%
# call the task


patrol_traj_map_layers = (
    create_polyline_layer.set_task_instance_id("patrol_traj_map_layers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
            all_geometry_are_none,
        ],
        unpack_depth=1,
    )
    .partial(
        layer_style={
            "get_width": 3,
            "width_units": "pixels",
            "color_column": "patrol_traj_colormap",
        },
        legend={"label_column": "station", "color_column": "patrol_traj_colormap"},
        tooltip_columns=["Start Time", "Duration (s)", "Speed (kph)"],
        **patrol_traj_map_layers_params,
    )
    .mapvalues(argnames=["geodataframe"], argvalues=rename_traj_display_columns)
)


# %% [markdown]
# ## Draw Ecomaps

# %%
# parameters

traj_ecomap_params = dict(
    view_state=...,
    widget_id=...,
)

# %%
# call the task


traj_ecomap = (
    draw_ecomap.set_task_instance_id("traj_ecomap")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        title=None,
        tile_layers=base_map_defs,
        north_arrow_style={"placement": "top-left"},
        legend_style={"placement": "bottom-right"},
        static=False,
        max_zoom=20,
        **traj_ecomap_params,
    )
    .mapvalues(argnames=["geo_layers"], argvalues=patrol_traj_map_layers)
)


# %% [markdown]
# ## Persist Ecomaps

# %%
# parameters

traj_ecomap_html_urls_params = dict(
    filename=...,
)

# %%
# call the task


traj_ecomap_html_urls = (
    persist_text.set_task_instance_id("traj_ecomap_html_urls")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="patrol_map",
        **traj_ecomap_html_urls_params,
    )
    .mapvalues(argnames=["text"], argvalues=traj_ecomap)
)


# %% [markdown]
# ## Summarize by Transport Type

# %%
# parameters

transport_summary_params = dict()

# %%
# call the task


transport_summary = (
    summarize_df.set_task_instance_id("transport_summary")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=customize_columns_internally,
        groupby_cols=["patrol_transport"],
        summary_params=[
            {
                "display_name": "Patrol Count",
                "aggregator": "nunique",
                "column": "patrol_id",
            },
            {
                "display_name": "Total Distance (km)",
                "aggregator": "sum",
                "column": "dist_meters",
                "original_unit": "m",
                "new_unit": "km",
            },
            {
                "display_name": "Total Duration (hours)",
                "aggregator": "sum",
                "column": "timespan_seconds",
                "original_unit": "s",
                "new_unit": "h",
                "decimal_places": 1,
            },
        ],
        reset_index=False,
        **transport_summary_params,
    )
    .call()
)


# %% [markdown]
# ## Summarize by Station

# %%
# parameters

station_summary_params = dict()

# %%
# call the task


station_summary = (
    summarize_df.set_task_instance_id("station_summary")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=customize_columns_internally,
        groupby_cols=["station"],
        summary_params=[
            {
                "display_name": "Patrol Count",
                "aggregator": "nunique",
                "column": "patrol_id",
            },
            {
                "display_name": "Total Distance (km)",
                "aggregator": "sum",
                "column": "dist_meters",
                "original_unit": "m",
                "new_unit": "km",
            },
            {
                "display_name": "Total Duration (hours)",
                "aggregator": "sum",
                "column": "timespan_seconds",
                "original_unit": "s",
                "new_unit": "h",
                "decimal_places": 1,
            },
        ],
        reset_index=True,
        **station_summary_params,
    )
    .call()
)


# %% [markdown]
# ## Draw Station Bar Chart

# %%
# parameters

patrol_bar_chart_params = dict(
    widget_id=...,
)

# %%
# call the task


patrol_bar_chart = (
    draw_bar_chart.set_task_instance_id("patrol_bar_chart")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        dataframe=station_summary,
        category="station",
        layout_kwargs=None,
        bar_chart_configs=[
            {
                "label": "Total Distance (km)",
                "column": "Total Distance (km)",
                "agg_func": "sum",
                "show_label": True,
                "style": {"marker_color": "#35b779"},
            },
            {
                "label": "Total Duration (hours)",
                "column": "Total Duration (hours)",
                "agg_func": "sum",
                "show_label": True,
                "style": {"marker_color": "#31688e"},
            },
        ],
        **patrol_bar_chart_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Bar Chart

# %%
# parameters

persist_bar_chart_params = dict(
    filename=...,
)

# %%
# call the task


persist_bar_chart = (
    persist_text.set_task_instance_id("persist_bar_chart")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        text=patrol_bar_chart,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="transport_bar_chart",
        **persist_bar_chart_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Transport Summary

# %%
# parameters

persist_transport_summary_params = dict(
    filename=...,
)

# %%
# call the task


persist_transport_summary = (
    persist_df_wrapper.set_task_instance_id("persist_transport_summary")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        df=transport_summary,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_prefix="transport_summary",
        filetypes=["csv"],
        sanitize=True,
        **persist_transport_summary_params,
    )
    .call()
)


# %% [markdown]
# ## Summarize by Mandate

# %%
# parameters

mandate_summary_params = dict()

# %%
# call the task


mandate_summary = (
    summarize_df.set_task_instance_id("mandate_summary")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=customize_columns_internally,
        groupby_cols=["patrol_mandate"],
        summary_params=[
            {
                "display_name": "Patrol Count",
                "aggregator": "nunique",
                "column": "patrol_id",
            },
            {
                "display_name": "Total Distance (km)",
                "aggregator": "sum",
                "column": "dist_meters",
                "original_unit": "m",
                "new_unit": "km",
            },
            {
                "display_name": "Total Duration (hours)",
                "aggregator": "sum",
                "column": "timespan_seconds",
                "original_unit": "s",
                "new_unit": "h",
                "decimal_places": 1,
            },
        ],
        reset_index=False,
        **mandate_summary_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Mandate Summary

# %%
# parameters

persist_mandate_summary_params = dict(
    filename=...,
)

# %%
# call the task


persist_mandate_summary = (
    persist_df_wrapper.set_task_instance_id("persist_mandate_summary")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        df=mandate_summary,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_prefix="mandate_summary",
        filetypes=["csv"],
        sanitize=True,
        **persist_mandate_summary_params,
    )
    .call()
)


# %% [markdown]
# ## Set Station Grouper

# %%
# parameters

station_groupers_params = dict()

# %%
# call the task


station_groupers = (
    set_groupers.set_task_instance_id("station_groupers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(groupers=[{"index_name": "station"}], **station_groupers_params)
    .call()
)


# %% [markdown]
# ## Split by Station

# %%
# parameters

split_by_station_params = dict()

# %%
# call the task


split_by_station = (
    split_groups.set_task_instance_id("split_by_station")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=customize_columns_internally,
        groupers=station_groupers,
        **split_by_station_params,
    )
    .call()
)


# %% [markdown]
# ## Summarize Rangers per Station

# %%
# parameters

ranger_summary_params = dict()

# %%
# call the task


ranger_summary = (
    summarize_df.set_task_instance_id("ranger_summary")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        groupby_cols=["patrol_leader_name"],
        summary_params=[
            {
                "display_name": "Patrol Count",
                "aggregator": "nunique",
                "column": "patrol_id",
            },
            {
                "display_name": "Total Distance (km)",
                "aggregator": "sum",
                "column": "dist_meters",
                "original_unit": "m",
                "new_unit": "km",
            },
            {
                "display_name": "Total Duration (hours)",
                "aggregator": "sum",
                "column": "timespan_seconds",
                "original_unit": "s",
                "new_unit": "h",
                "decimal_places": 1,
            },
        ],
        reset_index=False,
        **ranger_summary_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_by_station)
)


# %% [markdown]
# ## Persist Ranger Summary

# %%
# parameters

persist_ranger_summary_params = dict(
    filename=...,
)

# %%
# call the task


persist_ranger_summary = (
    persist_df_wrapper.set_task_instance_id("persist_ranger_summary")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_prefix="ranger_summary",
        filetypes=["csv"],
        sanitize=True,
        **persist_ranger_summary_params,
    )
    .mapvalues(argnames=["df"], argvalues=ranger_summary)
)


# %% [markdown]
# ## Set Report Groupers

# %%
# parameters

report_groupers_params = dict()

# %%
# call the task


report_groupers = (
    set_groupers.set_task_instance_id("report_groupers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        groupers=[{"index_name": "patrol_mandate"}, {"index_name": "station"}],
        **report_groupers_params,
    )
    .call()
)


# %% [markdown]
# ## Create Patrol Report

# %%
# parameters

create_patrol_report_params = dict(
    template_path=...,
)

# %%
# call the task


create_patrol_report = (
    create_docx.set_task_instance_id("create_patrol_report")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        context={
            "items": [
                {
                    "item_type": "timerange",
                    "key": "report_date",
                    "value": time_range,
                    "format": "%b %Y",
                },
                {
                    "item_type": "image",
                    "key": "patrol_maps",
                    "value": traj_ecomap_html_urls,
                    "screenshot_config": {"wait_for_timeout": 0},
                },
                {
                    "item_type": "image",
                    "key": "bar_chart",
                    "value": persist_bar_chart,
                    "screenshot_config": {"wait_for_timeout": 0},
                },
                {
                    "item_type": "table",
                    "key": "transport_summary",
                    "value": transport_summary,
                },
                {
                    "item_type": "table",
                    "key": "mandate_summary",
                    "value": mandate_summary,
                },
                {
                    "item_type": "table",
                    "key": "ranger_summary",
                    "value": ranger_summary,
                },
            ]
        },
        groupers=report_groupers,
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_prefix="mt_patrols_report",
        **create_patrol_report_params,
    )
    .call()
)


# %% [markdown]
# ## Create Dashboard

# %%
# parameters

patrol_dashboard_params = dict(
    warning=...,
)

# %%
# call the task


patrol_dashboard = (
    gather_dashboard.set_task_instance_id("patrol_dashboard")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        details=workflow_details,
        widgets=[],
        groupers=[{"index_name": "patrol_mandate"}],
        time_range=time_range,
        **patrol_dashboard_params,
    )
    .call()
)
