# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import json
import os

from ecoscope_workflows_core.tasks.config import set_bool_var as set_bool_var
from ecoscope_workflows_core.tasks.config import set_string_var as set_string_var
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope_workflows_core.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_custom.tasks.io import load_df as load_df
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_custom.tasks.results import create_docx as create_docx
from ecoscope_workflows_ext_custom.tasks.skip import maybe_skip_df as maybe_skip_df
from ecoscope_workflows_ext_custom.tasks.transformation import (
    apply_sql_query as apply_sql_query,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    drop_column_prefix as drop_column_prefix,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    create_polyline_layer as create_polyline_layer,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_bar_chart as draw_bar_chart,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_ecomap as draw_ecomap
from ecoscope_workflows_ext_ecoscope.tasks.results import set_base_maps as set_base_maps
from ecoscope_workflows_ext_ecoscope.tasks.skip import (
    all_geometry_are_none as all_geometry_are_none,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)

from ..params import Params


def main(params: Params):
    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    workflow_details = (
        set_workflow_details.validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        set_time_range.validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            time_format="%d %b %Y %H:%M:%S %Z", **(params_dict.get("time_range") or {})
        )
        .call()
    )

    patrol_obs = (
        load_df.validate()
        .set_task_instance_id("patrol_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("patrol_obs") or {}))
        .call()
    )

    get_timezone = (
        get_timezone_from_time_range.validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params_dict.get("get_timezone") or {}))
        .call()
    )

    convert_patrols_to_user_timezone = (
        convert_values_to_timezone.validate()
        .set_task_instance_id("convert_patrols_to_user_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_obs,
            timezone=get_timezone,
            columns=["fixtime"],
            **(params_dict.get("convert_patrols_to_user_timezone") or {}),
        )
        .call()
    )

    drop_extra_prefix_obs = (
        drop_column_prefix.validate()
        .set_task_instance_id("drop_extra_prefix_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_patrols_to_user_timezone,
            prefix="extra__",
            duplicate_strategy="suffix",
            **(params_dict.get("drop_extra_prefix_obs") or {}),
        )
        .call()
    )

    filter_patrol_obs = (
        apply_reloc_coord_filter.validate()
        .set_task_instance_id("filter_patrol_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_extra_prefix_obs,
            roi_gdf=None,
            roi_name=None,
            reset_index=False,
            bounding_box={
                "min_x": -180.0,
                "max_x": 180.0,
                "min_y": -90.0,
                "max_y": 90.0,
            },
            filter_point_coords=[
                {"x": 180.0, "y": 90.0},
                {"x": 0.0, "y": 0.0},
                {"x": 1.0, "y": 1.0},
            ],
            **(params_dict.get("filter_patrol_obs") or {}),
        )
        .call()
    )

    patrol_traj = (
        relocations_to_trajectory.validate()
        .set_task_instance_id("patrol_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            relocations=filter_patrol_obs, **(params_dict.get("patrol_traj") or {})
        )
        .call()
    )

    drop_extra_prefix_traj = (
        drop_column_prefix.validate()
        .set_task_instance_id("drop_extra_prefix_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_traj,
            prefix="extra__",
            duplicate_strategy="suffix",
            **(params_dict.get("drop_extra_prefix_traj") or {}),
        )
        .call()
    )

    customize_columns_internally = (
        map_columns.validate()
        .set_task_instance_id("customize_columns_internally")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_extra_prefix_traj,
            rename_columns={},
            drop_columns=["id"],
            retain_columns=[],
            raise_if_not_found=False,
            **(params_dict.get("customize_columns_internally") or {}),
        )
        .call()
    )

    customize_columns_traj = (
        map_columns.validate()
        .set_task_instance_id("customize_columns_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=customize_columns_internally,
            rename_columns={},
            retain_columns=[],
            raise_if_not_found=False,
            **(params_dict.get("customize_columns_traj") or {}),
        )
        .call()
    )

    sql_query_traj = (
        apply_sql_query.validate()
        .set_task_instance_id("sql_query_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=customize_columns_traj, **(params_dict.get("sql_query_traj") or {}))
        .call()
    )

    groupers = (
        set_groupers.validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("groupers") or {}))
        .call()
    )

    set_patrol_traj_color_column = (
        set_string_var.validate()
        .set_task_instance_id("set_patrol_traj_color_column")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("set_patrol_traj_color_column") or {}))
        .call()
    )

    traj_add_temporal_index = (
        add_temporal_index.validate()
        .set_task_instance_id("traj_add_temporal_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=sql_query_traj,
            time_col="segment_start",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params_dict.get("traj_add_temporal_index") or {}),
        )
        .call()
    )

    traj_colormap = (
        apply_color_map.validate()
        .set_task_instance_id("traj_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_add_temporal_index,
            colormap=[
                "#FF9600",
                "#F23B0E",
                "#A100CB",
                "#F04564",
                "#03421A",
                "#3089FF",
                "#E26FFF",
                "#8C1700",
                "#002960",
                "#FFD000",
                "#B62879",
                "#680078",
                "#005A56",
                "#0056C7",
                "#331878",
                "#E76826",
            ],
            input_column_name=set_patrol_traj_color_column,
            output_column_name="patrol_traj_colormap",
            **(params_dict.get("traj_colormap") or {}),
        )
        .call()
    )

    split_patrol_traj_groups = (
        split_groups.validate()
        .set_task_instance_id("split_patrol_traj_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_colormap,
            groupers=groupers,
            **(params_dict.get("split_patrol_traj_groups") or {}),
        )
        .call()
    )

    persist_patrol_traj = (
        persist_df_wrapper.validate()
        .set_task_instance_id("persist_patrol_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_prefix="patrol_trajectories",
            sanitize=True,
            **(params_dict.get("persist_patrol_traj") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_patrol_traj_groups)
    )

    set_skip_map = (
        set_bool_var.validate()
        .set_task_instance_id("set_skip_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("set_skip_map") or {}))
        .call()
    )

    skip_traj_map = (
        maybe_skip_df.validate()
        .set_task_instance_id("skip_traj_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(skip=set_skip_map, **(params_dict.get("skip_traj_map") or {}))
        .mapvalues(argnames=["df"], argvalues=split_patrol_traj_groups)
    )

    set_patrol_map_title = (
        set_string_var.validate()
        .set_task_instance_id("set_patrol_map_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            var="Patrol Trajectories Map",
            **(params_dict.get("set_patrol_map_title") or {}),
        )
        .call()
    )

    base_map_defs = (
        set_base_maps.validate()
        .set_task_instance_id("base_map_defs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            base_maps=[{"layer_name": "TERRAIN", "opacity": 1}],
            **(params_dict.get("base_map_defs") or {}),
        )
        .call()
    )

    rename_traj_display_columns = (
        map_columns.validate()
        .set_task_instance_id("rename_traj_display_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            raise_if_not_found=False,
            rename_columns={
                "segment_start": "Start Time",
                "timespan_seconds": "Duration (s)",
                "speed_kmhr": "Speed (kph)",
            },
            **(params_dict.get("rename_traj_display_columns") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=skip_traj_map)
    )

    patrol_traj_map_layers = (
        create_polyline_layer.validate()
        .set_task_instance_id("patrol_traj_map_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "get_width": 3,
                "width_units": "pixels",
                "color_column": "patrol_traj_colormap",
            },
            legend=None,
            tooltip_columns=["Start Time", "Duration (s)", "Speed (kph)"],
            **(params_dict.get("patrol_traj_map_layers") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=rename_traj_display_columns)
    )

    traj_ecomap = (
        draw_ecomap.validate()
        .set_task_instance_id("traj_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title=None,
            tile_layers=base_map_defs,
            north_arrow_style={"placement": "top-left"},
            legend_style=None,
            static=False,
            max_zoom=20,
            **(params_dict.get("traj_ecomap") or {}),
        )
        .mapvalues(argnames=["geo_layers"], argvalues=patrol_traj_map_layers)
    )

    traj_ecomap_html_urls = (
        persist_text.validate()
        .set_task_instance_id("traj_ecomap_html_urls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="patrol_map",
            **(params_dict.get("traj_ecomap_html_urls") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=traj_ecomap)
    )

    transport_summary = (
        summarize_df.validate()
        .set_task_instance_id("transport_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=sql_query_traj,
            groupby_cols=["patrol_transport"],
            summary_params=[
                {
                    "display_name": "Patrol Count",
                    "aggregator": "nunique",
                    "column": "patrol_id",
                },
                {
                    "display_name": "Total Distance (km)",
                    "aggregator": "sum",
                    "column": "dist_meters",
                    "original_unit": "m",
                    "new_unit": "km",
                },
                {
                    "display_name": "Total Duration (hours)",
                    "aggregator": "sum",
                    "column": "timespan_seconds",
                    "original_unit": "s",
                    "new_unit": "h",
                    "decimal_places": 1,
                },
            ],
            reset_index=False,
            **(params_dict.get("transport_summary") or {}),
        )
        .call()
    )

    station_summary = (
        summarize_df.validate()
        .set_task_instance_id("station_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=sql_query_traj,
            groupby_cols=["station"],
            summary_params=[
                {
                    "display_name": "Patrol Count",
                    "aggregator": "nunique",
                    "column": "patrol_id",
                },
                {
                    "display_name": "Total Distance (km)",
                    "aggregator": "sum",
                    "column": "dist_meters",
                    "original_unit": "m",
                    "new_unit": "km",
                },
                {
                    "display_name": "Total Duration (hours)",
                    "aggregator": "sum",
                    "column": "timespan_seconds",
                    "original_unit": "s",
                    "new_unit": "h",
                    "decimal_places": 1,
                },
            ],
            reset_index=True,
            **(params_dict.get("station_summary") or {}),
        )
        .call()
    )

    patrol_bar_chart = (
        draw_bar_chart.validate()
        .set_task_instance_id("patrol_bar_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=station_summary,
            category="station",
            bar_chart_configs=[
                {
                    "label": "Total Distance (km)",
                    "column": "Total Distance (km)",
                    "agg_func": "sum",
                    "show_label": True,
                    "style": {"marker_color": "#35b779"},
                },
                {
                    "label": "Total Duration (hours)",
                    "column": "Total Duration (hours)",
                    "agg_func": "sum",
                    "show_label": True,
                    "style": {"marker_color": "#31688e"},
                },
            ],
            **(params_dict.get("patrol_bar_chart") or {}),
        )
        .call()
    )

    persist_bar_chart = (
        persist_text.validate()
        .set_task_instance_id("persist_bar_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=patrol_bar_chart,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="transport_bar_chart",
            **(params_dict.get("persist_bar_chart") or {}),
        )
        .call()
    )

    persist_transport_summary = (
        persist_df_wrapper.validate()
        .set_task_instance_id("persist_transport_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            df=transport_summary,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_prefix="transport_summary",
            filetypes=["csv"],
            sanitize=True,
            **(params_dict.get("persist_transport_summary") or {}),
        )
        .call()
    )

    mandate_summary = (
        summarize_df.validate()
        .set_task_instance_id("mandate_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=sql_query_traj,
            groupby_cols=["patrol_mandate"],
            summary_params=[
                {
                    "display_name": "Patrol Count",
                    "aggregator": "nunique",
                    "column": "patrol_id",
                },
                {
                    "display_name": "Total Distance (km)",
                    "aggregator": "sum",
                    "column": "dist_meters",
                    "original_unit": "m",
                    "new_unit": "km",
                },
                {
                    "display_name": "Total Duration (hours)",
                    "aggregator": "sum",
                    "column": "timespan_seconds",
                    "original_unit": "s",
                    "new_unit": "h",
                    "decimal_places": 1,
                },
            ],
            reset_index=False,
            **(params_dict.get("mandate_summary") or {}),
        )
        .call()
    )

    persist_mandate_summary = (
        persist_df_wrapper.validate()
        .set_task_instance_id("persist_mandate_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            df=mandate_summary,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_prefix="mandate_summary",
            filetypes=["csv"],
            sanitize=True,
            **(params_dict.get("persist_mandate_summary") or {}),
        )
        .call()
    )

    station_groupers = (
        set_groupers.validate()
        .set_task_instance_id("station_groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupers=[{"index_name": "station"}],
            **(params_dict.get("station_groupers") or {}),
        )
        .call()
    )

    split_by_station = (
        split_groups.validate()
        .set_task_instance_id("split_by_station")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=sql_query_traj,
            groupers=station_groupers,
            **(params_dict.get("split_by_station") or {}),
        )
        .call()
    )

    ranger_summary = (
        summarize_df.validate()
        .set_task_instance_id("ranger_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupby_cols=["patrol_leader_name"],
            summary_params=[
                {
                    "display_name": "Patrol Count",
                    "aggregator": "nunique",
                    "column": "patrol_id",
                },
                {
                    "display_name": "Total Distance (km)",
                    "aggregator": "sum",
                    "column": "dist_meters",
                    "original_unit": "m",
                    "new_unit": "km",
                },
                {
                    "display_name": "Total Duration (hours)",
                    "aggregator": "sum",
                    "column": "timespan_seconds",
                    "original_unit": "s",
                    "new_unit": "h",
                    "decimal_places": 1,
                },
            ],
            reset_index=False,
            **(params_dict.get("ranger_summary") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_by_station)
    )

    persist_ranger_summary = (
        persist_df_wrapper.validate()
        .set_task_instance_id("persist_ranger_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_prefix="ranger_summary",
            filetypes=["csv"],
            sanitize=True,
            **(params_dict.get("persist_ranger_summary") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=ranger_summary)
    )

    report_groupers = (
        set_groupers.validate()
        .set_task_instance_id("report_groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupers=[{"index_name": "patrol_mandate"}, {"index_name": "station"}],
            **(params_dict.get("report_groupers") or {}),
        )
        .call()
    )

    create_patrol_report = (
        create_docx.validate()
        .set_task_instance_id("create_patrol_report")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            context={
                "items": [
                    {
                        "item_type": "timerange",
                        "key": "report_date",
                        "value": time_range,
                    },
                    {
                        "item_type": "image",
                        "key": "patrol_maps",
                        "value": traj_ecomap_html_urls,
                        "screenshot_config": {"wait_for_timeout": 0},
                    },
                    {
                        "item_type": "image",
                        "key": "bar_chart",
                        "value": persist_bar_chart,
                        "screenshot_config": {"wait_for_timeout": 0},
                    },
                    {
                        "item_type": "table",
                        "key": "transport_summary",
                        "value": transport_summary,
                    },
                    {
                        "item_type": "table",
                        "key": "mandate_summary",
                        "value": mandate_summary,
                    },
                    {
                        "item_type": "table",
                        "key": "ranger_summary",
                        "value": ranger_summary,
                    },
                ]
            },
            groupers=report_groupers,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_prefix="mt_patrols_report",
            **(params_dict.get("create_patrol_report") or {}),
        )
        .call()
    )

    patrol_dashboard = (
        gather_dashboard.validate()
        .set_task_instance_id("patrol_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[],
            groupers=groupers,
            time_range=time_range,
            **(params_dict.get("patrol_dashboard") or {}),
        )
        .call()
    )

    return patrol_dashboard
