# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import json
import os
import warnings  # 🧪

from ecoscope_workflows_core.graph import DependsOn, Graph, Node
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.io import (
    set_smart_connection as set_smart_connection,
)
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.testing import create_task_magicmock  # 🧪

get_patrol_observations_from_smart = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="get_patrol_observations_from_smart",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.config import set_bool_var as set_bool_var
from ecoscope_workflows_core.tasks.config import set_string_var as set_string_var
from ecoscope_workflows_core.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope_workflows_core.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_custom.tasks.results import create_docx as create_docx
from ecoscope_workflows_ext_custom.tasks.skip import maybe_skip_df as maybe_skip_df
from ecoscope_workflows_ext_custom.tasks.transformation import (
    apply_sql_query as apply_sql_query,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    drop_column_prefix as drop_column_prefix,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    create_polyline_layer as create_polyline_layer,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_bar_chart as draw_bar_chart,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_ecomap as draw_ecomap
from ecoscope_workflows_ext_ecoscope.tasks.results import set_base_maps as set_base_maps
from ecoscope_workflows_ext_ecoscope.tasks.skip import (
    all_geometry_are_none as all_geometry_are_none,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)

from ..params import Params


def main(params: Params):
    warnings.warn("This test script should not be used in production!")  # 🧪

    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    dependencies = {
        "workflow_details": [],
        "smart_client_name": [],
        "time_range": [],
        "patrol_obs": ["smart_client_name", "time_range"],
        "get_timezone": ["time_range"],
        "convert_patrols_to_user_timezone": ["patrol_obs", "get_timezone"],
        "drop_extra_prefix_obs": ["convert_patrols_to_user_timezone"],
        "filter_patrol_obs": ["drop_extra_prefix_obs"],
        "patrol_traj": ["filter_patrol_obs"],
        "drop_extra_prefix_traj": ["patrol_traj"],
        "customize_columns_internally": ["drop_extra_prefix_traj"],
        "customize_columns_traj": ["customize_columns_internally"],
        "sql_query_traj": ["customize_columns_traj"],
        "groupers": [],
        "set_patrol_traj_color_column": [],
        "traj_add_temporal_index": ["sql_query_traj", "groupers"],
        "traj_colormap": ["traj_add_temporal_index", "set_patrol_traj_color_column"],
        "split_patrol_traj_groups": ["traj_colormap", "groupers"],
        "persist_patrol_traj": ["split_patrol_traj_groups"],
        "set_skip_map": [],
        "skip_traj_map": ["set_skip_map", "split_patrol_traj_groups"],
        "set_patrol_map_title": [],
        "base_map_defs": [],
        "rename_traj_display_columns": ["skip_traj_map"],
        "patrol_traj_map_layers": ["rename_traj_display_columns"],
        "traj_ecomap": ["base_map_defs", "patrol_traj_map_layers"],
        "traj_ecomap_html_urls": ["traj_ecomap"],
        "transport_summary": ["sql_query_traj"],
        "patrol_bar_chart": ["transport_summary"],
        "persist_bar_chart": ["patrol_bar_chart"],
        "persist_transport_summary": ["transport_summary"],
        "station_groupers": [],
        "split_by_station": ["sql_query_traj", "station_groupers"],
        "ranger_summary": ["split_by_station"],
        "persist_ranger_summary": ["ranger_summary"],
        "report_groupers": [],
        "create_patrol_report": [
            "time_range",
            "traj_ecomap_html_urls",
            "persist_bar_chart",
            "transport_summary",
            "ranger_summary",
            "report_groupers",
        ],
        "patrol_dashboard": ["workflow_details", "groupers", "time_range"],
    }

    nodes = {
        "workflow_details": Node(
            async_task=set_workflow_details.validate()
            .set_task_instance_id("workflow_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("workflow_details") or {}),
            method="call",
        ),
        "smart_client_name": Node(
            async_task=set_smart_connection.validate()
            .set_task_instance_id("smart_client_name")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("smart_client_name") or {}),
            method="call",
        ),
        "time_range": Node(
            async_task=set_time_range.validate()
            .set_task_instance_id("time_range")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_format": "%d %b %Y %H:%M:%S %Z",
            }
            | (params_dict.get("time_range") or {}),
            method="call",
        ),
        "patrol_obs": Node(
            async_task=get_patrol_observations_from_smart.validate()
            .set_task_instance_id("patrol_obs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("smart_client_name"),
                "time_range": DependsOn("time_range"),
            }
            | (params_dict.get("patrol_obs") or {}),
            method="call",
        ),
        "get_timezone": Node(
            async_task=get_timezone_from_time_range.validate()
            .set_task_instance_id("get_timezone")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_range": DependsOn("time_range"),
            }
            | (params_dict.get("get_timezone") or {}),
            method="call",
        ),
        "convert_patrols_to_user_timezone": Node(
            async_task=convert_values_to_timezone.validate()
            .set_task_instance_id("convert_patrols_to_user_timezone")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("patrol_obs"),
                "timezone": DependsOn("get_timezone"),
                "columns": [
                    "fixtime",
                ],
            }
            | (params_dict.get("convert_patrols_to_user_timezone") or {}),
            method="call",
        ),
        "drop_extra_prefix_obs": Node(
            async_task=drop_column_prefix.validate()
            .set_task_instance_id("drop_extra_prefix_obs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("convert_patrols_to_user_timezone"),
                "prefix": "extra__",
                "duplicate_strategy": "suffix",
            }
            | (params_dict.get("drop_extra_prefix_obs") or {}),
            method="call",
        ),
        "filter_patrol_obs": Node(
            async_task=apply_reloc_coord_filter.validate()
            .set_task_instance_id("filter_patrol_obs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("drop_extra_prefix_obs"),
                "roi_gdf": None,
                "roi_name": None,
                "reset_index": False,
                "bounding_box": {
                    "min_x": -180.0,
                    "max_x": 180.0,
                    "min_y": -90.0,
                    "max_y": 90.0,
                },
                "filter_point_coords": [
                    {
                        "x": 180.0,
                        "y": 90.0,
                    },
                    {
                        "x": 0.0,
                        "y": 0.0,
                    },
                    {
                        "x": 1.0,
                        "y": 1.0,
                    },
                ],
            }
            | (params_dict.get("filter_patrol_obs") or {}),
            method="call",
        ),
        "patrol_traj": Node(
            async_task=relocations_to_trajectory.validate()
            .set_task_instance_id("patrol_traj")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "relocations": DependsOn("filter_patrol_obs"),
            }
            | (params_dict.get("patrol_traj") or {}),
            method="call",
        ),
        "drop_extra_prefix_traj": Node(
            async_task=drop_column_prefix.validate()
            .set_task_instance_id("drop_extra_prefix_traj")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("patrol_traj"),
                "prefix": "extra__",
                "duplicate_strategy": "suffix",
            }
            | (params_dict.get("drop_extra_prefix_traj") or {}),
            method="call",
        ),
        "customize_columns_internally": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("customize_columns_internally")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("drop_extra_prefix_traj"),
                "drop_columns": [
                    "id",
                ],
                "raise_if_not_found": False,
            }
            | (params_dict.get("customize_columns_internally") or {}),
            method="call",
        ),
        "customize_columns_traj": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("customize_columns_traj")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("customize_columns_internally"),
                "raise_if_not_found": False,
            }
            | (params_dict.get("customize_columns_traj") or {}),
            method="call",
        ),
        "sql_query_traj": Node(
            async_task=apply_sql_query.validate()
            .set_task_instance_id("sql_query_traj")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("customize_columns_traj"),
            }
            | (params_dict.get("sql_query_traj") or {}),
            method="call",
        ),
        "groupers": Node(
            async_task=set_groupers.validate()
            .set_task_instance_id("groupers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("groupers") or {}),
            method="call",
        ),
        "set_patrol_traj_color_column": Node(
            async_task=set_string_var.validate()
            .set_task_instance_id("set_patrol_traj_color_column")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("set_patrol_traj_color_column") or {}),
            method="call",
        ),
        "traj_add_temporal_index": Node(
            async_task=add_temporal_index.validate()
            .set_task_instance_id("traj_add_temporal_index")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("sql_query_traj"),
                "time_col": "segment_start",
                "groupers": DependsOn("groupers"),
                "cast_to_datetime": True,
                "format": "mixed",
            }
            | (params_dict.get("traj_add_temporal_index") or {}),
            method="call",
        ),
        "traj_colormap": Node(
            async_task=apply_color_map.validate()
            .set_task_instance_id("traj_colormap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("traj_add_temporal_index"),
                "colormap": [
                    "#FF9600",
                    "#F23B0E",
                    "#A100CB",
                    "#F04564",
                    "#03421A",
                    "#3089FF",
                    "#E26FFF",
                    "#8C1700",
                    "#002960",
                    "#FFD000",
                    "#B62879",
                    "#680078",
                    "#005A56",
                    "#0056C7",
                    "#331878",
                    "#E76826",
                ],
                "input_column_name": DependsOn("set_patrol_traj_color_column"),
                "output_column_name": "patrol_traj_colormap",
            }
            | (params_dict.get("traj_colormap") or {}),
            method="call",
        ),
        "split_patrol_traj_groups": Node(
            async_task=split_groups.validate()
            .set_task_instance_id("split_patrol_traj_groups")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("traj_colormap"),
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("split_patrol_traj_groups") or {}),
            method="call",
        ),
        "persist_patrol_traj": Node(
            async_task=persist_df_wrapper.validate()
            .set_task_instance_id("persist_patrol_traj")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_prefix": "patrol_trajectories",
                "sanitize": True,
            }
            | (params_dict.get("persist_patrol_traj") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("split_patrol_traj_groups"),
            },
        ),
        "set_skip_map": Node(
            async_task=set_bool_var.validate()
            .set_task_instance_id("set_skip_map")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("set_skip_map") or {}),
            method="call",
        ),
        "skip_traj_map": Node(
            async_task=maybe_skip_df.validate()
            .set_task_instance_id("skip_traj_map")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "skip": DependsOn("set_skip_map"),
            }
            | (params_dict.get("skip_traj_map") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("split_patrol_traj_groups"),
            },
        ),
        "set_patrol_map_title": Node(
            async_task=set_string_var.validate()
            .set_task_instance_id("set_patrol_map_title")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "var": "Patrol Trajectories Map",
            }
            | (params_dict.get("set_patrol_map_title") or {}),
            method="call",
        ),
        "base_map_defs": Node(
            async_task=set_base_maps.validate()
            .set_task_instance_id("base_map_defs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "base_maps": [
                    {
                        "layer_name": "TERRAIN",
                        "opacity": 1,
                    },
                ],
            }
            | (params_dict.get("base_map_defs") or {}),
            method="call",
        ),
        "rename_traj_display_columns": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("rename_traj_display_columns")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "raise_if_not_found": False,
                "rename_columns": {
                    "segment_start": "Start Time",
                    "timespan_seconds": "Duration (s)",
                    "speed_kmhr": "Speed (kph)",
                },
            }
            | (params_dict.get("rename_traj_display_columns") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("skip_traj_map"),
            },
        ),
        "patrol_traj_map_layers": Node(
            async_task=create_polyline_layer.validate()
            .set_task_instance_id("patrol_traj_map_layers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                    all_geometry_are_none,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "layer_style": {
                    "get_width": 3,
                    "width_units": "pixels",
                    "color_column": "patrol_traj_colormap",
                },
                "legend": None,
                "tooltip_columns": [
                    "Start Time",
                    "Duration (s)",
                    "Speed (kph)",
                ],
            }
            | (params_dict.get("patrol_traj_map_layers") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geodataframe"],
                "argvalues": DependsOn("rename_traj_display_columns"),
            },
        ),
        "traj_ecomap": Node(
            async_task=draw_ecomap.validate()
            .set_task_instance_id("traj_ecomap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": None,
                "tile_layers": DependsOn("base_map_defs"),
                "north_arrow_style": {
                    "placement": "top-left",
                },
                "legend_style": None,
                "static": False,
                "max_zoom": 20,
            }
            | (params_dict.get("traj_ecomap") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geo_layers"],
                "argvalues": DependsOn("patrol_traj_map_layers"),
            },
        ),
        "traj_ecomap_html_urls": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("traj_ecomap_html_urls")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "patrol_map",
            }
            | (params_dict.get("traj_ecomap_html_urls") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("traj_ecomap"),
            },
        ),
        "transport_summary": Node(
            async_task=summarize_df.validate()
            .set_task_instance_id("transport_summary")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("sql_query_traj"),
                "groupby_cols": [
                    "patrol_transport",
                ],
                "summary_params": [
                    {
                        "display_name": "# Patrols",
                        "aggregator": "nunique",
                        "column": "patrol_id",
                    },
                    {
                        "display_name": "Total Hours",
                        "aggregator": "sum",
                        "column": "timespan_seconds",
                        "original_unit": "s",
                        "new_unit": "h",
                    },
                    {
                        "display_name": "Total Distance (km)",
                        "aggregator": "sum",
                        "column": "dist_meters",
                        "original_unit": "m",
                        "new_unit": "km",
                    },
                ],
                "reset_index": True,
            }
            | (params_dict.get("transport_summary") or {}),
            method="call",
        ),
        "patrol_bar_chart": Node(
            async_task=draw_bar_chart.validate()
            .set_task_instance_id("patrol_bar_chart")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "dataframe": DependsOn("transport_summary"),
                "category": "patrol_transport",
                "bar_chart_configs": [
                    {
                        "label": "Total Hours",
                        "column": "Total Hours",
                        "agg_func": "sum",
                    },
                    {
                        "label": "Total Distance (km)",
                        "column": "Total Distance (km)",
                        "agg_func": "sum",
                    },
                ],
            }
            | (params_dict.get("patrol_bar_chart") or {}),
            method="call",
        ),
        "persist_bar_chart": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_bar_chart")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "text": DependsOn("patrol_bar_chart"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "transport_bar_chart",
            }
            | (params_dict.get("persist_bar_chart") or {}),
            method="call",
        ),
        "persist_transport_summary": Node(
            async_task=persist_df_wrapper.validate()
            .set_task_instance_id("persist_transport_summary")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("transport_summary"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_prefix": "transport_summary",
                "filetypes": [
                    "csv",
                ],
                "sanitize": True,
            }
            | (params_dict.get("persist_transport_summary") or {}),
            method="call",
        ),
        "station_groupers": Node(
            async_task=set_groupers.validate()
            .set_task_instance_id("station_groupers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "groupers": [
                    {
                        "index_name": "station",
                    },
                ],
            }
            | (params_dict.get("station_groupers") or {}),
            method="call",
        ),
        "split_by_station": Node(
            async_task=split_groups.validate()
            .set_task_instance_id("split_by_station")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("sql_query_traj"),
                "groupers": DependsOn("station_groupers"),
            }
            | (params_dict.get("split_by_station") or {}),
            method="call",
        ),
        "ranger_summary": Node(
            async_task=summarize_df.validate()
            .set_task_instance_id("ranger_summary")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "groupby_cols": [
                    "patrol_leader_name",
                ],
                "summary_params": [
                    {
                        "display_name": "# Patrols",
                        "aggregator": "nunique",
                        "column": "patrol_id",
                    },
                    {
                        "display_name": "Total Hours",
                        "aggregator": "sum",
                        "column": "timespan_seconds",
                        "original_unit": "s",
                        "new_unit": "h",
                    },
                    {
                        "display_name": "Total Distance (km)",
                        "aggregator": "sum",
                        "column": "dist_meters",
                        "original_unit": "m",
                        "new_unit": "km",
                    },
                ],
                "reset_index": True,
            }
            | (params_dict.get("ranger_summary") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("split_by_station"),
            },
        ),
        "persist_ranger_summary": Node(
            async_task=persist_df_wrapper.validate()
            .set_task_instance_id("persist_ranger_summary")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_prefix": "ranger_summary",
                "filetypes": [
                    "csv",
                ],
                "sanitize": True,
            }
            | (params_dict.get("persist_ranger_summary") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("ranger_summary"),
            },
        ),
        "report_groupers": Node(
            async_task=set_groupers.validate()
            .set_task_instance_id("report_groupers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "groupers": [
                    {
                        "index_name": "patrol_mandate",
                    },
                    {
                        "index_name": "station",
                    },
                ],
            }
            | (params_dict.get("report_groupers") or {}),
            method="call",
        ),
        "create_patrol_report": Node(
            async_task=create_docx.validate()
            .set_task_instance_id("create_patrol_report")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "context": {
                    "items": [
                        {
                            "item_type": "text",
                            "key": "title",
                            "value": "MT Patrols Report",
                        },
                        {
                            "item_type": "timerange",
                            "key": "report_date",
                            "value": DependsOn("time_range"),
                        },
                        {
                            "item_type": "image",
                            "key": "patrol_maps",
                            "value": DependsOn("traj_ecomap_html_urls"),
                            "screenshot_config": {
                                "wait_for_timeout": 0,
                            },
                        },
                        {
                            "item_type": "image",
                            "key": "bar_chart",
                            "value": DependsOn("persist_bar_chart"),
                            "screenshot_config": {
                                "wait_for_timeout": 0,
                            },
                        },
                        {
                            "item_type": "table",
                            "key": "transport_stats",
                            "value": DependsOn("transport_summary"),
                        },
                        {
                            "item_type": "table",
                            "key": "ranger_tables",
                            "value": DependsOn("ranger_summary"),
                        },
                    ],
                },
                "groupers": DependsOn("report_groupers"),
                "output_dir": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_prefix": "mt_patrols_report",
            }
            | (params_dict.get("create_patrol_report") or {}),
            method="call",
        ),
        "patrol_dashboard": Node(
            async_task=gather_dashboard.validate()
            .set_task_instance_id("patrol_dashboard")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "details": DependsOn("workflow_details"),
                "groupers": DependsOn("groupers"),
                "time_range": DependsOn("time_range"),
            }
            | (params_dict.get("patrol_dashboard") or {}),
            method="call",
        ),
    }
    graph = Graph(dependencies=dependencies, nodes=nodes)
    results = graph.execute()
    return results
