# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import os
from typing import Any

from ecoscope.platform.tasks.config import (
    set_list_of_string_vars as set_list_of_string_vars,
)
from ecoscope.platform.tasks.config import set_string_var as set_string_var
from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.groupby import split_groups as split_groups
from ecoscope.platform.tasks.io import persist_df_wrapper as persist_df_wrapper
from ecoscope.platform.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope.platform.tasks.transformation import apply_color_map as apply_color_map
from ecoscope.platform.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)
from ecoscope.platform.tasks.transformation import apply_sql_query as apply_sql_query
from ecoscope.platform.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope.platform.tasks.transformation import (
    drop_column_prefix as drop_column_prefix,
)
from ecoscope.platform.tasks.transformation import explode as explode
from ecoscope.platform.tasks.transformation import (
    extract_column_as_type as extract_column_as_type,
)
from ecoscope.platform.tasks.transformation import (
    extract_value_from_json_column as extract_value_from_json_column,
)
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope.platform.tasks.transformation import map_values as map_values
from ecoscope_workflows_ext_custom.tasks.io import load_df as load_df
from ecoscope_workflows_ext_custom.tasks.transformation import (
    combine_string_lists as combine_string_lists,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    get_collection_item as get_collection_item,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    invert_string_lists as invert_string_lists,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    merge_two_dataframes as merge_two_dataframes,
)
from wt_contracts import validate as _validate
from wt_task import task

from .. import metadata as _metadata


def main(params: dict[str, Any], validate_params_schema: bool = True):
    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%d %b %Y %H:%M:%S %Z", **(params.get("time_range") or {}))
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params.get("get_timezone") or {}))
        .call()
    )

    report_scope = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("report_scope")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("report_scope") or {}))
        .call()
    )

    triangle_patrol_types = (
        task(set_list_of_string_vars)
        .validate()
        .set_task_instance_id("triangle_patrol_types")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("triangle_patrol_types") or {}))
        .call()
    )

    reserve_patrol_types = (
        task(set_list_of_string_vars)
        .validate()
        .set_task_instance_id("reserve_patrol_types")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("reserve_patrol_types") or {}))
        .call()
    )

    include_areas = (
        task(get_collection_item)
        .validate()
        .set_task_instance_id("include_areas")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            collection={
                "Mara Triangle & Reserve": ["Mara Triangle", "Reserve"],
                "Mara Triangle only": ["Mara Triangle"],
                "Reserve only": ["Reserve"],
            },
            key=report_scope,
            default=None,
            raise_on_missing=True,
            **(params.get("include_areas") or {}),
        )
        .call()
    )

    selected_patrol_types = (
        task(combine_string_lists)
        .validate()
        .set_task_instance_id("selected_patrol_types")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            lists={
                "Mara Triangle": triangle_patrol_types,
                "Reserve": reserve_patrol_types,
            },
            include_keys=include_areas,
            **(params.get("selected_patrol_types") or {}),
        )
        .call()
    )

    patrol_area_value_map = (
        task(invert_string_lists)
        .validate()
        .set_task_instance_id("patrol_area_value_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            lists={
                "Mara Triangle": triangle_patrol_types,
                "Reserve": reserve_patrol_types,
            },
            include_keys=include_areas,
            **(params.get("patrol_area_value_map") or {}),
        )
        .call()
    )

    patrol_obs = (
        task(load_df)
        .validate()
        .set_task_instance_id("patrol_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(deserialize_json=False, **(params.get("patrol_obs") or {}))
        .call()
    )

    patrol_info_events = (
        task(load_df)
        .validate()
        .set_task_instance_id("patrol_info_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(deserialize_json=True, **(params.get("patrol_info_events") or {}))
        .call()
    )

    explode_event_patrols = (
        task(explode)
        .validate()
        .set_task_instance_id("explode_event_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_info_events,
            column_name="patrols",
            ignore_index=True,
            **(params.get("explode_event_patrols") or {}),
        )
        .call()
    )

    event_patrol_id = (
        task(map_columns)
        .validate()
        .set_task_instance_id("event_patrol_id")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=explode_event_patrols,
            rename_columns={"patrols": "patrol_id"},
            drop_columns=[],
            retain_columns=[],
            raise_if_not_found=True,
            **(params.get("event_patrol_id") or {}),
        )
        .call()
    )

    extract_ranger_name = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_ranger_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=event_patrol_id,
            column_name="event_details",
            field_name_options=["Patrol leader", "Team_leader"],
            output_type="str",
            output_column_name="ranger_name",
            **(params.get("extract_ranger_name") or {}),
        )
        .call()
    )

    extract_mandate = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_mandate")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_ranger_name,
            column_name="event_details",
            field_name_options=["Mandate", "mandate"],
            output_type="str",
            output_column_name="patrol_mandate",
            **(params.get("extract_mandate") or {}),
        )
        .call()
    )

    extract_team_name = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_team_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_mandate,
            column_name="event_details",
            field_name_options=["Team name", "Team_name"],
            output_type="str",
            output_column_name="team_name",
            **(params.get("extract_team_name") or {}),
        )
        .call()
    )

    extract_transport = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_transport")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_team_name,
            column_name="event_details",
            field_name_options=["Transport type", "Transport_type"],
            output_type="str",
            output_column_name="patrol_transport",
            **(params.get("extract_transport") or {}),
        )
        .call()
    )

    patrol_attribute_columns = (
        task(map_columns)
        .validate()
        .set_task_instance_id("patrol_attribute_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_transport,
            rename_columns={},
            drop_columns=[],
            retain_columns=[
                "patrol_id",
                "ranger_name",
                "patrol_mandate",
                "team_name",
                "patrol_transport",
            ],
            raise_if_not_found=False,
            **(params.get("patrol_attribute_columns") or {}),
        )
        .call()
    )

    patrol_attributes = (
        task(apply_sql_query)
        .validate()
        .set_task_instance_id("patrol_attributes")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_attribute_columns,
            query="SELECT patrol_id,\n       MAX(ranger_name) AS ranger_name,\n       MAX(patrol_mandate) AS patrol_mandate,\n       MAX(team_name) AS team_name,\n       MAX(patrol_transport) AS patrol_transport\nFROM df GROUP BY patrol_id\n",
            **(params.get("patrol_attributes") or {}),
        )
        .call()
    )

    convert_obs_to_user_timezone = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_obs_to_user_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_obs,
            timezone=get_timezone,
            columns=["fixtime", "patrol_start_time", "patrol_end_time"],
            **(params.get("convert_obs_to_user_timezone") or {}),
        )
        .call()
    )

    drop_extra_prefix_obs = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_extra_prefix_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_obs_to_user_timezone,
            prefix="extra__",
            duplicate_strategy="suffix",
            **(params.get("drop_extra_prefix_obs") or {}),
        )
        .call()
    )

    rename_patrol_columns = (
        task(map_columns)
        .validate()
        .set_task_instance_id("rename_patrol_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_extra_prefix_obs,
            drop_columns=["patrol_type"],
            rename_columns={
                "patrol_type__value": "patrol_type",
                "patrol_type__display": "patrol_type_display",
            },
            retain_columns=[],
            raise_if_not_found=False,
            **(params.get("rename_patrol_columns") or {}),
        )
        .call()
    )

    filter_patrol_obs = (
        task(apply_reloc_coord_filter)
        .validate()
        .set_task_instance_id("filter_patrol_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=rename_patrol_columns,
            roi_gdf=None,
            roi_name=None,
            reset_index=False,
            bounding_box={
                "min_x": -180.0,
                "max_x": 180.0,
                "min_y": -90.0,
                "max_y": 90.0,
            },
            filter_point_coords=[
                {"x": 180.0, "y": 90.0},
                {"x": 0.0, "y": 0.0},
                {"x": 1.0, "y": 1.0},
            ],
            **(params.get("filter_patrol_obs") or {}),
        )
        .call()
    )

    patrol_traj = (
        task(relocations_to_trajectory)
        .validate()
        .set_task_instance_id("patrol_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(relocations=filter_patrol_obs, **(params.get("patrol_traj") or {}))
        .call()
    )

    drop_extra_prefix_traj = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_extra_prefix_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_traj,
            prefix="extra__",
            duplicate_strategy="suffix",
            **(params.get("drop_extra_prefix_traj") or {}),
        )
        .call()
    )

    traj_with_attributes = (
        task(merge_two_dataframes)
        .validate()
        .set_task_instance_id("traj_with_attributes")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            left=drop_extra_prefix_traj,
            right=patrol_attributes,
            how="left",
            on="patrol_id",
            fillna_value="Unknown",
            **(params.get("traj_with_attributes") or {}),
        )
        .call()
    )

    copy_patrol_type = (
        task(extract_column_as_type)
        .validate()
        .set_task_instance_id("copy_patrol_type")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_with_attributes,
            column_name="patrol_type",
            output_type="str",
            output_column_name="patrol_area",
            **(params.get("copy_patrol_type") or {}),
        )
        .call()
    )

    derive_patrol_area = (
        task(map_values)
        .validate()
        .set_task_instance_id("derive_patrol_area")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=copy_patrol_type,
            column_name="patrol_area",
            value_map=patrol_area_value_map,
            missing_values="replace",
            replacement="Unknown",
            **(params.get("derive_patrol_area") or {}),
        )
        .call()
    )

    traj_add_temporal_index = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("traj_add_temporal_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=derive_patrol_area,
            time_col="segment_start",
            groupers=[{"index_name": "patrol_area"}, {"index_name": "patrol_mandate"}],
            cast_to_datetime=True,
            format="mixed",
            **(params.get("traj_add_temporal_index") or {}),
        )
        .call()
    )

    traj_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("traj_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_add_temporal_index,
            colormap=[
                "#FF9600",
                "#F23B0E",
                "#A100CB",
                "#F04564",
                "#03421A",
                "#3089FF",
                "#E26FFF",
                "#8C1700",
                "#002960",
                "#FFD000",
                "#B62879",
                "#680078",
                "#005A56",
                "#0056C7",
                "#331878",
                "#E76826",
            ],
            input_column_name="team_name",
            output_column_name="team_colormap",
            **(params.get("traj_colormap") or {}),
        )
        .call()
    )

    split_by_area = (
        task(split_groups)
        .validate()
        .set_task_instance_id("split_by_area")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_colormap,
            groupers=[{"index_name": "patrol_area"}],
            **(params.get("split_by_area") or {}),
        )
        .call()
    )

    split_map_groups = (
        task(split_groups)
        .validate()
        .set_task_instance_id("split_map_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_colormap,
            groupers=[{"index_name": "patrol_area"}, {"index_name": "patrol_mandate"}],
            **(params.get("split_map_groups") or {}),
        )
        .call()
    )

    persist_patrol_traj = (
        task(persist_df_wrapper)
        .validate()
        .set_task_instance_id("persist_patrol_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_prefix="patrol_trajectories",
            sanitize=True,
            **(params.get("persist_patrol_traj") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_by_area)
    )

    patrol_dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("patrol_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[],
            groupers=[{"index_name": "patrol_area"}],
            time_range=time_range,
            **(params.get("patrol_dashboard") or {}),
        )
        .call()
    )

    return patrol_dashboard
